"""Add strategy, position group, and position group transaction tables

Revision ID: 5ff98bcc14f4
Revises: 6f247580bf47
Create Date: 2025-05-14 10:43:07.769273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff98bcc14f4'
down_revision: Union[str, None] = '6f247580bf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('position_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tastytrade_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_groups_account_id'), 'position_groups', ['account_id'], unique=False)
    op.create_index(op.f('ix_position_groups_strategy_id'), 'position_groups', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_position_groups_user_id'), 'position_groups', ['user_id'], unique=False)
    op.create_table('position_group_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['position_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['tastytrade_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_group_transactions_group_id'), 'position_group_transactions', ['group_id'], unique=False)
    op.create_index(op.f('ix_position_group_transactions_transaction_id'), 'position_group_transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_group_transactions_transaction_id'), table_name='position_group_transactions')
    op.drop_index(op.f('ix_position_group_transactions_group_id'), table_name='position_group_transactions')
    op.drop_table('position_group_transactions')
    op.drop_index(op.f('ix_position_groups_user_id'), table_name='position_groups')
    op.drop_index(op.f('ix_position_groups_strategy_id'), table_name='position_groups')
    op.drop_index(op.f('ix_position_groups_account_id'), table_name='position_groups')
    op.drop_table('position_groups')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
